version: 2

projects:

- name: "terraform"
  workflow: "terraform"
  dir: "terraform"
  workspace: "default"
  terraform_version: "v0.11.7"
  autoplan:
    enabled: false
  apply_requirements:
    - "approved"

- name: "cloudformation"
  workflow: "cloudformation"
  dir: "."
  autoplan:
    enabled: false
  apply_requirements:
    - "approved"

workflows:
  terraform:
    plan:
      steps:
      - run: "init-terraform"
      - run: "terraform plan -no-color -input=false -var-file prod.tfvars -out $PLANFILE"
    apply:
      steps:
      - run: "init-terraform"
      - run: "terraform apply -no-color -input=false -var-file prod.tfvars $PLANFILE"

  cloudformation:
    plan:
      steps:
      - run: "make cf/package STAGE=prod"
      - run: "make cf/plan STAGE=prod"
    apply:
      steps:
      - run: "make cf/deploy STAGE=prod"
      - run: "make cf/sync STAGE=prod"
